# Generated by Django 4.0.3 on 2022-04-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarbagePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='garbage_image', verbose_name='Фотография бедствия')),
                ('coords', models.CharField(max_length=512, verbose_name='Гео данные')),
                ('name', models.CharField(max_length=256, verbose_name='Название организации')),
            ],
            options={
                'verbose_name': 'Местонахождение бедствия',
                'verbose_name_plural': 'Местонахождения бедствия',
                'db_table': 'garbage_place',
            },
        ),
    ]
